version: '3.9'
name: web
services:

  web:
    image: file-management:${WEB-VERSION}
    container_name: file-management
    build:
      context: file-management
      dockerfile: Dockerfile
    ports:
      - "7010:7010"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_BOOT_ADMIN_CLIENT_URL: http://spring-admin:9020/api/spring/admin

networks:
  backend:
    driver: bridge