version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin1
      POSTGRES_PASSWORD: admin1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data