version: '3.9'
services:
  admin-backend:
    image: mkrezka/admin-backend:latest
    container_name: admin-backend
    ports:
      - "7000:7000"
    networks:
      - mk
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_SERVER}
      SPRING_BOOT_ADMIN_CLIENT_URL: ${SPRING_BOOT_ADMIN_URL}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}/admin
  web-backend:
    image: mkrezka/web-backend:latest
    container_name: web-backend
    ports:
      - "7010:7010"
    networks:
      - mk
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_SERVER}
      SPRING_DATA_MONGODB_URI: ${MONGO_URI}/web?authSource=admin
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      SPRING_BOOT_ADMIN_CLIENT_URL: ${SPRING_BOOT_ADMIN_URL}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_URL}
  um-backend:
    image: mkrezka/um-backend:latest
    container_name: um-backend
    ports:
      - "7020:7020"
    networks:
      - mk
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES}
      SPRING_BOOT_ADMIN_CLIENT_URL: ${SPRING_BOOT_ADMIN_URL}
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: ${EUREKA_CLIENT_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_DATASOURCE_URL: ${POSTGRES_URL}/um

networks:
  mk:
    external: true