spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:local-admin;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_schema: local-admin
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    schemas: local-admin
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      properties:
        ack: all
        retries: 0
        batch-size: 16384
        linger.ms: 1
        buffer.memory: 16777216
        schema.registry.url: http://localhost:9095
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
security:
  enabled: false