version: '3.9'
name: web
services:

  web:
    image: web:${WEB-VERSION}
    container_name: web
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "7010:7010"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_BOOT_ADMIN_CLIENT_URL: http://spring-admin:9020/api/spring/admin

networks:
  backend:
    driver: bridge