version: '3.9'
name: auth
services:

  auth:
    image: auth:${AUTH-VERSION}
    container_name: auth
    build:
      dockerfile: Dockerfile
    ports:
      - "9010:9010"
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_BOOT_ADMIN_CLIENT_URL: http://spring-admin:9020/api/spring/admin

networks:
  backend:
    driver: bridge