spring:
  boot:
    admin:
      client:
        instance:
          name: ${spring.application.name}
        url: http://localhost:9020/api/spring/admin
        username: ${SPRING.ADMIN.USERNAME:Admin}
        password: ${SPRING.ADMIN.PASSWORD:i4z5ccfPGux7jWB8}

eureka:
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://${SPRING.ADMIN.USERNAME:Admin}:${SPRING.ADMIN.PASSWORD:i4z5ccfPGux7jWB8}@localhost:9020/api/spring/eureka
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    instance-info-replication-interval-seconds: 30

management:
  endpoint:
    health:
      show-details: always
    loggers:
      enabled: true
    env:
      enabled: true
      show-values: always
      post:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'